package https.www_bizapedia_com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-28T20:52:05.945-05:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "https://www.bizapedia.com/", name = "bdmserviceSoap")
@XmlSeeAlso({https.www_bizapedia.ObjectFactory.class})
public interface BdmserviceSoap {

    @WebMethod(operationName = "LCBFN", action = "https://www.bizapedia.com/LCBFN")
    @RequestWrapper(localName = "LCBFN", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LCBFN")
    @ResponseWrapper(localName = "LCBFNResponse", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LCBFNResponse")
    @WebResult(name = "LCBFNResult", targetNamespace = "https://www.bizapedia.com/")
    public https.www_bizapedia.Company lcbfn(
        @WebParam(name = "k", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String k,
        @WebParam(name = "pa", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String pa,
        @WebParam(name = "fn", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String fn
    );

    @WebMethod(operationName = "GACC", action = "https://www.bizapedia.com/GACC")
    @RequestWrapper(localName = "GACC", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.GACC")
    @ResponseWrapper(localName = "GACCResponse", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.GACCResponse")
    @WebResult(name = "GACCResult", targetNamespace = "https://www.bizapedia.com/")
    public int gacc(
        @WebParam(name = "k", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String k
    );

    @WebMethod(operationName = "LT", action = "https://www.bizapedia.com/LT")
    @RequestWrapper(localName = "LT", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LT")
    @ResponseWrapper(localName = "LTResponse", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LTResponse")
    @WebResult(name = "LTResult", targetNamespace = "https://www.bizapedia.com/")
    public https.www_bizapedia.TrademarkList lt(
        @WebParam(name = "k", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String k,
        @WebParam(name = "tm", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String tm,
        @WebParam(name = "tmo", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String tmo
    );

    @WebMethod(operationName = "LCSBN", action = "https://www.bizapedia.com/LCSBN")
    @RequestWrapper(localName = "LCSBN", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LCSBN")
    @ResponseWrapper(localName = "LCSBNResponse", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LCSBNResponse")
    @WebResult(name = "LCSBNResult", targetNamespace = "https://www.bizapedia.com/")
    public https.www_bizapedia.CompanyList lcsbn(
        @WebParam(name = "k", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String k,
        @WebParam(name = "n", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String n,
        @WebParam(name = "c", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String c,
        @WebParam(name = "pa", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String pa
    );

    @WebMethod(operationName = "LA", action = "https://www.bizapedia.com/LA")
    @RequestWrapper(localName = "LA", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LA")
    @ResponseWrapper(localName = "LAResponse", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LAResponse")
    @WebResult(name = "LAResult", targetNamespace = "https://www.bizapedia.com/")
    public https.www_bizapedia.AddressLists la(
        @WebParam(name = "k", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String k,
        @WebParam(name = "a", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String a,
        @WebParam(name = "c", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String c,
        @WebParam(name = "pa", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String pa,
        @WebParam(name = "pc", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String pc
    );

    @WebMethod(operationName = "LP", action = "https://www.bizapedia.com/LP")
    @RequestWrapper(localName = "LP", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LP")
    @ResponseWrapper(localName = "LPResponse", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LPResponse")
    @WebResult(name = "LPResult", targetNamespace = "https://www.bizapedia.com/")
    public https.www_bizapedia.CompanyPrincipalList lp(
        @WebParam(name = "k", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String k,
        @WebParam(name = "fnm", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String fnm,
        @WebParam(name = "lnm", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String lnm,
        @WebParam(name = "c", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String c,
        @WebParam(name = "pa", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String pa
    );

    @WebMethod(operationName = "LCBN", action = "https://www.bizapedia.com/LCBN")
    @RequestWrapper(localName = "LCBN", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LCBN")
    @ResponseWrapper(localName = "LCBNResponse", targetNamespace = "https://www.bizapedia.com/", className = "https.www_bizapedia.LCBNResponse")
    @WebResult(name = "LCBNResult", targetNamespace = "https://www.bizapedia.com/")
    public https.www_bizapedia.Company lcbn(
        @WebParam(name = "k", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String k,
        @WebParam(name = "pa", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String pa,
        @WebParam(name = "n", targetNamespace = "https://www.bizapedia.com/")
        java.lang.String n
    );
}
